set SERVER_LOCALE_LIST=fr,en
set LOCALE_LIST=fr,en
set SERVER_MODEL_NAME=Curam

set CURAM_DIR=%~dp0
set SERVER_DIR=%CURAM_DIR%EJBServer
set CURAMSDEJ=%CURAM_DIR%CuramSDEJ
set CLIENT_PROJECT_NAME=Curam
set CLIENT_DIR=%CURAM_DIR%webclient
set CURAMCDEJ=%CURAM_DIR%CuramCDEJ

set DEVTOOLS=C:\DevTools

@REM  overridden in BDCEnvironment.bat and BDCBenefitGroupEnvironment
set CLIENT_COMPONENT_ORDER=custom,PlatformConfig,CommonIntake,Intake,ReferralsLite,PCR,CREOLEProgramRecommendation,SummaryViews,CitizenContextViewer,WorkspaceServices,CitizenWorkspaceAdmin,FundPM,Appeal,SupervisorAppeals,DecisionAssist,DynamicEvidence,CEFWidgets,CMIS,IntelligentEvidenceGathering,IEGAdmin,Datastore,Editors,SupervisorWorkspace,Verification,ServicePlans,sample,CTMInfrastructure,SamplePublicAccess,AdvancedEvidenceSharing,EvidenceBroker,CuramFinancialAdapter,CuramMDAdapter,Advisor,EvidenceSharing,PDC,ValidationManager,SmartNavigator

set SERVER_COMPONENT_ORDER=custom,PlatformConfig,Appeal,CommonIntake,Intake,ReferralsLite,PCR,CREOLEProgramRecommendation,SummaryViews,CitizenWorkspace,CitizenContextViewer,WorkspaceServices,CitizenWorkspaceAdmin,FundPM,SupervisorAppeals,DecisionAssist,DynamicEvidence,CEFWidgets,CMISInfrastructure,CMIS,IntelligentEvidenceGathering,Datastore,Editors,SupervisorWorkspace,Verification,ServicePlans,sample,CTMInfrastructure,SamplePublicAccess,AdvancedEvidenceSharing,EvidenceBroker,CuramFinancialAdapter,CuramMDAdapter,CREOLEInfrastructure,Advisor,EvidenceSharing,PDC,PFMAppViews,Workflow,ValidationManager,SmartNavigator



::Environment variables set at foundations level
if exist %CURAM_DIR%CustomEnvironment.bat call %CURAM_DIR%CustomEnvironment.bat
