//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a geophysical location described by postal information.
 *
 * <p>
 * Java class for AddressType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="AddressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressFullText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressPrivateMailboxText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressSecondaryUnitText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressStreet" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressRecipientName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressCityName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressCountry" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressProvince" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressPostalCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressPostalExtensionCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}AddressCategoryText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"addressFullText", "addressPrivateMailboxText",
    "addressSecondaryUnitText", "addressStreet", "addressRecipientName",
    "addressCityName", "addressCountry", "addressProvince",
    "addressPostalCode", "addressPostalExtensionCode",
    "addressCategoryText" })
public class AddressType extends ObjectType {

  @XmlElement(name = "AddressFullText", nillable = true)
  protected List<TextType> addressFullText;

  @XmlElement(name = "AddressPrivateMailboxText", nillable = true)
  protected List<TextType> addressPrivateMailboxText;

  @XmlElement(name = "AddressSecondaryUnitText", nillable = true)
  protected List<TextType> addressSecondaryUnitText;

  @XmlElement(name = "AddressStreet", nillable = true)
  protected List<StreetType> addressStreet;

  @XmlElement(name = "AddressRecipientName", nillable = true)
  protected List<TextType> addressRecipientName;

  @XmlElement(name = "AddressCityName", nillable = true)
  protected List<TextType> addressCityName;

  @XmlElement(name = "AddressCountry", nillable = true)
  protected List<CountryType> addressCountry;

  @XmlElement(name = "AddressProvince")
  protected List<ProvinceType> addressProvince;

  @XmlElement(name = "AddressPostalCode", nillable = true)
  protected List<String> addressPostalCode;

  @XmlElement(name = "AddressPostalExtensionCode", nillable = true)
  protected List<String> addressPostalExtensionCode;

  @XmlElement(name = "AddressCategoryText", nillable = true)
  protected List<TextType> addressCategoryText;

  /**
   * Gets the value of the addressFullText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the addressFullText
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressFullText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getAddressFullText() {

    if (addressFullText == null) {
      addressFullText = new ArrayList<TextType>();
    }
    return this.addressFullText;
  }

  /**
   * Gets the value of the addressPrivateMailboxText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * addressPrivateMailboxText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressPrivateMailboxText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getAddressPrivateMailboxText() {

    if (addressPrivateMailboxText == null) {
      addressPrivateMailboxText = new ArrayList<TextType>();
    }
    return this.addressPrivateMailboxText;
  }

  /**
   * Gets the value of the addressSecondaryUnitText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * addressSecondaryUnitText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressSecondaryUnitText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getAddressSecondaryUnitText() {

    if (addressSecondaryUnitText == null) {
      addressSecondaryUnitText = new ArrayList<TextType>();
    }
    return this.addressSecondaryUnitText;
  }

  /**
   * Gets the value of the addressStreet property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the addressStreet
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressStreet().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link StreetType }
   *
   *
   */
  public List<StreetType> getAddressStreet() {

    if (addressStreet == null) {
      addressStreet = new ArrayList<StreetType>();
    }
    return this.addressStreet;
  }

  /**
   * Gets the value of the addressRecipientName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * addressRecipientName property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressRecipientName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getAddressRecipientName() {

    if (addressRecipientName == null) {
      addressRecipientName = new ArrayList<TextType>();
    }
    return this.addressRecipientName;
  }

  /**
   * Gets the value of the addressCityName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the addressCityName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressCityName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getAddressCityName() {

    if (addressCityName == null) {
      addressCityName = new ArrayList<TextType>();
    }
    return this.addressCityName;
  }

  /**
   * Gets the value of the addressCountry property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the addressCountry
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressCountry().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link CountryType }
   *
   *
   */
  public List<CountryType> getAddressCountry() {

    if (addressCountry == null) {
      addressCountry = new ArrayList<CountryType>();
    }
    return this.addressCountry;
  }

  /**
   * Gets the value of the addressProvince property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the addressProvince
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressProvince().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ProvinceType }
   *
   *
   */
  public List<ProvinceType> getAddressProvince() {

    if (addressProvince == null) {
      addressProvince = new ArrayList<ProvinceType>();
    }
    return this.addressProvince;
  }

  /**
   * Gets the value of the addressPostalCode property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * addressPostalCode property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressPostalCode().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link String }
   *
   *
   */
  public List<String> getAddressPostalCode() {

    if (addressPostalCode == null) {
      addressPostalCode = new ArrayList<String>();
    }
    return this.addressPostalCode;
  }

  /**
   * Gets the value of the addressPostalExtensionCode property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * addressPostalExtensionCode property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressPostalExtensionCode().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link String }
   *
   *
   */
  public List<String> getAddressPostalExtensionCode() {

    if (addressPostalExtensionCode == null) {
      addressPostalExtensionCode = new ArrayList<String>();
    }
    return this.addressPostalExtensionCode;
  }

  /**
   * Gets the value of the addressCategoryText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * addressCategoryText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddressCategoryText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getAddressCategoryText() {

    if (addressCategoryText == null) {
      addressCategoryText = new ArrayList<TextType>();
    }
    return this.addressCategoryText;
  }

}
