//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.28 at 11:59:40 AM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a benefit offered or delivered by programs.
 *
 * <p>
 * Java class for BenefitType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="BenefitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitAbbreviationText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitCountry" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitDescriptionText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitProgram" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"benefitAbbreviationText", "benefitCountry",
    "benefitDescriptionText", "benefitIdentification", "benefitName",
    "benefitProgram", "contactMailingAddress" })
public class BenefitType extends ResourceType {

  @XmlElement(name = "BenefitAbbreviationText")
  protected TextType benefitAbbreviationText;

  @XmlElement(name = "BenefitCountry")
  protected CountryType benefitCountry;

  @XmlElement(name = "BenefitDescriptionText")
  protected TextType benefitDescriptionText;

  @XmlElement(name = "BenefitIdentification")
  protected List<IdentificationType> benefitIdentification;

  @XmlElement(name = "BenefitName")
  protected TextType benefitName;

  @XmlElement(name = "BenefitProgram")
  protected ProgramType benefitProgram;

  @XmlElement(name = "ContactMailingAddress", nillable = true)
  protected List<AddressType> contactMailingAddress;

  /**
   * Gets the value of the benefitAbbreviationText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getBenefitAbbreviationText() {

    return benefitAbbreviationText;
  }

  /**
   * Sets the value of the benefitAbbreviationText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setBenefitAbbreviationText(final TextType value) {

    this.benefitAbbreviationText = value;
  }

  /**
   * Gets the value of the benefitCountry property.
   *
   * @return
   * possible object is
   * {@link CountryType }
   *
   */
  public CountryType getBenefitCountry() {

    return benefitCountry;
  }

  /**
   * Sets the value of the benefitCountry property.
   *
   * @param value
   * allowed object is
   * {@link CountryType }
   *
   */
  public void setBenefitCountry(final CountryType value) {

    this.benefitCountry = value;
  }

  /**
   * Gets the value of the benefitDescriptionText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getBenefitDescriptionText() {

    return benefitDescriptionText;
  }

  /**
   * Sets the value of the benefitDescriptionText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setBenefitDescriptionText(final TextType value) {

    this.benefitDescriptionText = value;
  }

  /**
   * Gets the value of the benefitIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * benefitIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getBenefitIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getBenefitIdentification() {

    if (benefitIdentification == null) {
      benefitIdentification = new ArrayList<IdentificationType>();
    }
    return this.benefitIdentification;
  }

  /**
   * Gets the value of the benefitName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getBenefitName() {

    return benefitName;
  }

  /**
   * Sets the value of the benefitName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setBenefitName(final TextType value) {

    this.benefitName = value;
  }

  /**
   * Gets the value of the benefitProgram property.
   *
   * @return
   * possible object is
   * {@link ProgramType }
   *
   */
  public ProgramType getBenefitProgram() {

    return benefitProgram;
  }

  /**
   * Sets the value of the benefitProgram property.
   *
   * @param value
   * allowed object is
   * {@link ProgramType }
   *
   */
  public void setBenefitProgram(final ProgramType value) {

    this.benefitProgram = value;
  }

  public List<AddressType> getContactMailingAddress() {

    if (contactMailingAddress == null) {
      contactMailingAddress = new ArrayList<AddressType>();
    }
    return this.contactMailingAddress;
  }

}
