//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.28 at 11:59:40 AM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for Information about an application for a program benefit.
 *
 * <p>
 * Java class for BenefitApplicationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="BenefitApplicationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}Applicant" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationBenefit" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationChannelText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationCountry" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationProgram" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationProvince" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplicationStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}CountryOfAgreementCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitApplicationType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"applicant", "benefitApplicationBenefit",
    "benefitApplicationChannelText", "benefitApplicationCountry",
    "benefitApplicationDate", "benefitApplicationIdentification",
    "benefitApplicationProgram", "benefitApplicationProvince",
    "benefitApplicationStatus", "countryOfAgreementCode" })
public class BenefitApplicationType extends ResourceType {

  @XmlElement(name = "Applicant", nillable = true)
  protected ClientType applicant;

  @XmlElement(name = "BenefitApplicationBenefit")
  protected List<BenefitType> benefitApplicationBenefit;

  @XmlElement(name = "BenefitApplicationChannelText")
  protected TextType benefitApplicationChannelText;

  @XmlElement(name = "BenefitApplicationCountry")
  protected CountryType benefitApplicationCountry;

  @XmlElement(name = "BenefitApplicationDate")
  protected DateType benefitApplicationDate;

  @XmlElement(name = "BenefitApplicationIdentification")
  protected List<IdentificationType> benefitApplicationIdentification;

  @XmlElement(name = "BenefitApplicationProgram")
  protected ProgramType benefitApplicationProgram;

  @XmlElement(name = "BenefitApplicationProvince")
  protected ProvinceType benefitApplicationProvince;

  @XmlElement(name = "BenefitApplicationStatus")
  protected List<StatusType> benefitApplicationStatus;

  @XmlElement(name = "CountryOfAgreementCode", nillable = true)
  protected TextType countryOfAgreementCode;

  /**
   * Gets the value of the applicant property.
   *
   * @return
   * possible object is
   * {@link ClientType }
   *
   */
  public ClientType getApplicant() {

    return applicant;
  }

  /**
   * Sets the value of the applicant property.
   *
   * @param value
   * allowed object is
   * {@link ClientType }
   *
   */
  public void setApplicant(final ClientType value) {

    this.applicant = value;
  }

  /**
   * Gets the value of the benefitApplicationBenefit property.
   *
   * @return
   * possible object is
   * {@link BenefitType }
   *
   */
  public List<BenefitType> getBenefitApplicationBenefit() {

    if (benefitApplicationBenefit == null) {
      benefitApplicationBenefit = new ArrayList<BenefitType>();
    }
    return this.benefitApplicationBenefit;
  }

  /**
   * Gets the value of the benefitApplicationChannelText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getBenefitApplicationChannelText() {

    return benefitApplicationChannelText;
  }

  /**
   * Sets the value of the benefitApplicationChannelText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setBenefitApplicationChannelText(final TextType value) {

    this.benefitApplicationChannelText = value;
  }

  /**
   * Gets the value of the benefitApplicationCountry property.
   *
   * @return
   * possible object is
   * {@link CountryType }
   *
   */
  public CountryType getBenefitApplicationCountry() {

    return benefitApplicationCountry;
  }

  /**
   * Sets the value of the benefitApplicationCountry property.
   *
   * @param value
   * allowed object is
   * {@link CountryType }
   *
   */
  public void setBenefitApplicationCountry(final CountryType value) {

    this.benefitApplicationCountry = value;
  }

  /**
   * Gets the value of the benefitApplicationDate property.
   *
   * @return
   * possible object is
   * {@link DateType }
   *
   */
  public DateType getBenefitApplicationDate() {

    return benefitApplicationDate;
  }

  /**
   * Sets the value of the benefitApplicationDate property.
   *
   * @param value
   * allowed object is
   * {@link DateType }
   *
   */
  public void setBenefitApplicationDate(final DateType value) {

    this.benefitApplicationDate = value;
  }

  /**
   * Gets the value of the benefitApplicationIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * benefitApplicationIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getBenefitApplicationIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getBenefitApplicationIdentification() {

    if (benefitApplicationIdentification == null) {
      benefitApplicationIdentification = new ArrayList<IdentificationType>();
    }
    return this.benefitApplicationIdentification;
  }

  /**
   * Gets the value of the benefitApplicationProgram property.
   *
   * @return
   * possible object is
   * {@link ProgramType }
   *
   */
  public ProgramType getBenefitApplicationProgram() {

    return benefitApplicationProgram;
  }

  /**
   * Sets the value of the benefitApplicationProgram property.
   *
   * @param value
   * allowed object is
   * {@link ProgramType }
   *
   */
  public void setBenefitApplicationProgram(final ProgramType value) {

    this.benefitApplicationProgram = value;
  }

  /**
   * Gets the value of the benefitApplicationProvince property.
   *
   * @return
   * possible object is
   * {@link ProvinceType }
   *
   */
  public ProvinceType getBenefitApplicationProvince() {

    return benefitApplicationProvince;
  }

  /**
   * Sets the value of the benefitApplicationProvince property.
   *
   * @param value
   * allowed object is
   * {@link ProvinceType }
   *
   */
  public void setBenefitApplicationProvince(final ProvinceType value) {

    this.benefitApplicationProvince = value;
  }

  /**
   * Gets the value of the benefitApplicationStatus property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * benefitApplicationStatus property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getBenefitApplicationStatus().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link StatusType }
   *
   *
   */
  public List<StatusType> getBenefitApplicationStatus() {

    if (benefitApplicationStatus == null) {
      benefitApplicationStatus = new ArrayList<StatusType>();
    }
    return this.benefitApplicationStatus;
  }

  /**
   * Gets the value of the countryOfAgreementCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getCountryOfAgreementCode() {

    return countryOfAgreementCode;
  }

  /**
   * Sets the value of the countryOfAgreementCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setCountryOfAgreementCode(final TextType value) {

    this.countryOfAgreementCode = value;
  }

}
