//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for the client resource.
 *
 * <p>
 * Java class for ClientType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ClientType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ClientIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonContactInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonBirthDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonBirthLocation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}PersonSINIdentification" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}PersonGenderText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonHumanResourceIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}PersonMaritalStatusCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}PersonPreferredLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonPrimaryLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonSecondaryLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonSexText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonDeathDate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"clientIdentification", "personName",
    "personContactInformation", "personBirthDate", "personBirthLocation",
    "personSINIdentification", "personGenderText",
    "personHumanResourceIdentification", "personMaritalStatusCode",
    "personPreferredLanguage", "personPrimaryLanguage",
    "personSecondaryLanguage", "personSexText", "personDeathDate" })
public class ClientType extends ResourceType {

  @XmlElement(name = "ClientIdentification", nillable = true)
  protected List<IdentificationType> clientIdentification;

  @XmlElement(name = "PersonName",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected List<PersonNameType> personName;

  @XmlElement(name = "PersonContactInformation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected List<ContactInformationType> personContactInformation;

  @XmlElement(name = "PersonBirthDate",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected DateType personBirthDate;

  @XmlElement(name = "PersonBirthLocation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LocationType personBirthLocation;

  @XmlElement(name = "PersonSINIdentification", nillable = true)
  protected IdentificationType personSINIdentification;

  @XmlElement(name = "PersonGenderText", nillable = true)
  protected TextType personGenderText;

  @XmlElement(name = "PersonHumanResourceIdentification",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected List<IdentificationType> personHumanResourceIdentification;

  @XmlElement(name = "PersonMaritalStatusCode", nillable = true)
  protected List<TextType> personMaritalStatusCode;

  @XmlElement(name = "PersonPreferredLanguage", nillable = true)
  protected LanguageType personPreferredLanguage;

  @XmlElement(name = "PersonPrimaryLanguage",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LanguageType personPrimaryLanguage;

  @XmlElement(name = "PersonSecondaryLanguage",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LanguageType personSecondaryLanguage;

  @XmlElement(name = "PersonSexText",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType personSexText;

  @XmlElement(name = "PersonDeathDate",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected DateType personDeathDate;

  /**
   * Gets the value of the clientIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * clientIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getClientIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getClientIdentification() {

    if (clientIdentification == null) {
      clientIdentification = new ArrayList<IdentificationType>();
    }
    return this.clientIdentification;
  }

  /**
   * Gets the value of the personName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link PersonNameType }
   *
   *
   */
  public List<PersonNameType> getPersonName() {

    if (personName == null) {
      personName = new ArrayList<PersonNameType>();
    }
    return this.personName;
  }

  /**
   * Gets the value of the personContactInformation property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personContactInformation property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonContactInformation().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ContactInformationType }
   *
   *
   */
  public List<ContactInformationType> getPersonContactInformation() {

    if (personContactInformation == null) {
      personContactInformation = new ArrayList<ContactInformationType>();
    }
    return this.personContactInformation;
  }

  /**
   * Gets the value of the personBirthDate property.
   *
   * @return
   * possible object is
   * {@link DateType }
   *
   */
  public DateType getPersonBirthDate() {

    return personBirthDate;
  }

  /**
   * Sets the value of the personBirthDate property.
   *
   * @param value
   * allowed object is
   * {@link DateType }
   *
   */
  public void setPersonBirthDate(final DateType value) {

    this.personBirthDate = value;
  }

  /**
   * Gets the value of the personBirthLocation property.
   *
   * @return
   * possible object is
   * {@link LocationType }
   *
   */
  public LocationType getPersonBirthLocation() {

    return personBirthLocation;
  }

  /**
   * Sets the value of the personBirthLocation property.
   *
   * @param value
   * allowed object is
   * {@link LocationType }
   *
   */
  public void setPersonBirthLocation(final LocationType value) {

    this.personBirthLocation = value;
  }

  /**
   * Gets the value of the personSINIdentification property.
   *
   * @return
   * possible object is
   * {@link IdentificationType }
   *
   */
  public IdentificationType getPersonSINIdentification() {

    return personSINIdentification;
  }

  /**
   * Sets the value of the personSINIdentification property.
   *
   * @param value
   * allowed object is
   * {@link IdentificationType }
   *
   */
  public void setPersonSINIdentification(final IdentificationType value) {

    this.personSINIdentification = value;
  }

  /**
   * Gets the value of the personGenderText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getPersonGenderText() {

    return personGenderText;
  }

  /**
   * Sets the value of the personGenderText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setPersonGenderText(final TextType value) {

    this.personGenderText = value;
  }

  /**
   * Gets the value of the personHumanResourceIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personHumanResourceIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonHumanResourceIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getPersonHumanResourceIdentification() {

    if (personHumanResourceIdentification == null) {
      personHumanResourceIdentification = new ArrayList<IdentificationType>();
    }
    return this.personHumanResourceIdentification;
  }

  /**
   * Gets the value of the personMaritalStatusCode property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personMaritalStatusCode property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonMaritalStatusCode().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonMaritalStatusCode() {

    if (personMaritalStatusCode == null) {
      personMaritalStatusCode = new ArrayList<TextType>();
    }
    return this.personMaritalStatusCode;
  }

  /**
   * Gets the value of the personPreferredLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getPersonPreferredLanguage() {

    return personPreferredLanguage;
  }

  /**
   * Sets the value of the personPreferredLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setPersonPreferredLanguage(final LanguageType value) {

    this.personPreferredLanguage = value;
  }

  /**
   * Gets the value of the personPrimaryLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getPersonPrimaryLanguage() {

    return personPrimaryLanguage;
  }

  /**
   * Sets the value of the personPrimaryLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setPersonPrimaryLanguage(final LanguageType value) {

    this.personPrimaryLanguage = value;
  }

  /**
   * Gets the value of the personSecondaryLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getPersonSecondaryLanguage() {

    return personSecondaryLanguage;
  }

  /**
   * Sets the value of the personSecondaryLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setPersonSecondaryLanguage(final LanguageType value) {

    this.personSecondaryLanguage = value;
  }

  /**
   * Gets the value of the personSexText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getPersonSexText() {

    return personSexText;
  }

  /**
   * Sets the value of the personSexText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setPersonSexText(final TextType value) {

    this.personSexText = value;
  }

  /**
   * Gets the value of the personDeathDate property.
   *
   * @return
   * possible object is
   * {@link DateType }
   *
   */
  public DateType getPersonDeathDate() {

    return personDeathDate;
  }

  /**
   * Sets the value of the personDeathDate property.
   *
   * @param value
   * allowed object is
   * {@link DateType }
   *
   */
  public void setPersonDeathDate(final DateType value) {

    this.personDeathDate = value;
  }

}
