//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for how to contact a person or an organization.
 *
 * <p>
 * Java class for ContactInformationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ContactInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ContactEmailID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ContactMailingAddress" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ContactTelephoneNumber" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ContactInformationDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactInformationType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"contactEmailID", "contactMailingAddress",
    "contactTelephoneNumber", "contactInformationDescriptionText" })
public class ContactInformationType extends ObjectType {

  @XmlElement(name = "ContactEmailID", nillable = true)
  protected List<String> contactEmailID;

  @XmlElement(name = "ContactMailingAddress", nillable = true)
  protected List<AddressType> contactMailingAddress;

  @XmlElement(name = "ContactTelephoneNumber", nillable = true)
  protected List<TelephoneNumberType> contactTelephoneNumber;

  @XmlElement(name = "ContactInformationDescriptionText", nillable = true)
  protected List<TextType> contactInformationDescriptionText;

  /**
   * Gets the value of the contactEmailID property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the contactEmailID
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getContactEmailID().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link String }
   *
   *
   */
  public List<String> getContactEmailID() {

    if (contactEmailID == null) {
      contactEmailID = new ArrayList<String>();
    }
    return this.contactEmailID;
  }

  /**
   * Gets the value of the contactMailingAddress property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * contactMailingAddress property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getContactMailingAddress().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link AddressType }
   *
   *
   */
  public List<AddressType> getContactMailingAddress() {

    if (contactMailingAddress == null) {
      contactMailingAddress = new ArrayList<AddressType>();
    }
    return this.contactMailingAddress;
  }

  /**
   * Gets the value of the contactTelephoneNumber property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * contactTelephoneNumber property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getContactTelephoneNumber().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TelephoneNumberType }
   *
   *
   */
  public List<TelephoneNumberType> getContactTelephoneNumber() {

    if (contactTelephoneNumber == null) {
      contactTelephoneNumber = new ArrayList<TelephoneNumberType>();
    }
    return this.contactTelephoneNumber;
  }

  /**
   * Gets the value of the contactInformationDescriptionText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * contactInformationDescriptionText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getContactInformationDescriptionText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getContactInformationDescriptionText() {

    if (contactInformationDescriptionText == null) {
      contactInformationDescriptionText = new ArrayList<TextType>();
    }
    return this.contactInformationDescriptionText;
  }

}
