//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for the content data used by a template to populate a
 * document section
 *
 * <p>
 * Java class for CorrespondenceContentType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="CorrespondenceContentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}CorrespondenceContentCategoryText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}Benefit" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}BenefitApplication" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}Client" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}Organization" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}Program" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RelatedPerson" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ServiceOffice" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrespondenceContentType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"correspondenceContentCategoryText", "benefit",
    "benefitApplication", "client", "organization", "program",
    "relatedPerson", "serviceOffice" })
public class CorrespondenceContentType extends ObjectType {

  @XmlElement(name = "CorrespondenceContentCategoryText")
  protected TextType correspondenceContentCategoryText;

  @XmlElement(name = "Benefit")
  protected BenefitType benefit;

  @XmlElement(name = "BenefitApplication")
  protected BenefitApplicationType benefitApplication;

  @XmlElement(name = "Client")
  protected ClientType client;

  @XmlElement(name = "Organization")
  protected List<OrganizationType1> organization;

  @XmlElement(name = "Program")
  protected ProgramType program;

  @XmlElement(name = "RelatedPerson")
  protected List<RelatedPersonType> relatedPerson;

  @XmlElement(name = "ServiceOffice")
  protected List<ServiceOfficeType> serviceOffice;

  /**
   * Gets the value of the correspondenceContentCategoryText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getCorrespondenceContentCategoryText() {

    return correspondenceContentCategoryText;
  }

  /**
   * Sets the value of the correspondenceContentCategoryText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setCorrespondenceContentCategoryText(final TextType value) {

    this.correspondenceContentCategoryText = value;
  }

  /**
   * Gets the value of the benefit property.
   *
   * @return
   * possible object is
   * {@link BenefitType }
   *
   */
  public BenefitType getBenefit() {

    return benefit;
  }

  /**
   * Sets the value of the benefit property.
   *
   * @param value
   * allowed object is
   * {@link BenefitType }
   *
   */
  public void setBenefit(final BenefitType value) {

    this.benefit = value;
  }

  /**
   * Gets the value of the benefitApplication property.
   *
   * @return
   * possible object is
   * {@link BenefitApplicationType }
   *
   */
  public BenefitApplicationType getBenefitApplication() {

    return benefitApplication;
  }

  /**
   * Sets the value of the benefitApplication property.
   *
   * @param value
   * allowed object is
   * {@link BenefitApplicationType }
   *
   */
  public void setBenefitApplication(final BenefitApplicationType value) {

    this.benefitApplication = value;
  }

  /**
   * Gets the value of the client property.
   *
   * @return
   * possible object is
   * {@link ClientType }
   *
   */
  public ClientType getClient() {

    return client;
  }

  /**
   * Sets the value of the client property.
   *
   * @param value
   * allowed object is
   * {@link ClientType }
   *
   */
  public void setClient(final ClientType value) {

    this.client = value;
  }

  /**
   * Gets the value of the organization property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the organization
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getOrganization().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link OrganizationType1 }
   *
   *
   */
  public List<OrganizationType1> getOrganization() {

    if (organization == null) {
      organization = new ArrayList<OrganizationType1>();
    }
    return this.organization;
  }

  /**
   * Gets the value of the program property.
   *
   * @return
   * possible object is
   * {@link ProgramType }
   *
   */
  public ProgramType getProgram() {

    return program;
  }

  /**
   * Sets the value of the program property.
   *
   * @param value
   * allowed object is
   * {@link ProgramType }
   *
   */
  public void setProgram(final ProgramType value) {

    this.program = value;
  }

  /**
   * Gets the value of the relatedPerson property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the relatedPerson
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getRelatedPerson().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link RelatedPersonType }
   *
   *
   */
  public List<RelatedPersonType> getRelatedPerson() {

    if (relatedPerson == null) {
      relatedPerson = new ArrayList<RelatedPersonType>();
    }
    return this.relatedPerson;
  }

  /**
   * Gets the value of the serviceOffice property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the serviceOffice
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getServiceOffice().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ServiceOfficeType }
   *
   *
   */
  public List<ServiceOfficeType> getServiceOffice() {

    if (serviceOffice == null) {
      serviceOffice = new ArrayList<ServiceOfficeType>();
    }
    return this.serviceOffice;
  }

}
