//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The data type for any written or electronic communication exchanged
 * between two or more parties. A correspondence can be a letter, an email, a
 * voicemail
 * or notes.
 *
 * <p>
 * Java class for CorrespondenceType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="CorrespondenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}CorrespondenceRecipient" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCategoryID" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCategoryName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}DocumentContent" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIdentification" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIssuanceLocation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIssueDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSource" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentStatus" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSubjectText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSubmitter" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentTitleText" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrespondenceType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"correspondenceRecipient", "documentCategoryID",
    "documentCategoryName", "documentContent", "documentIdentification",
    "documentIssuanceLocation", "documentIssueDate", "documentLanguage",
    "documentSource", "documentStatus", "documentSubjectText",
    "documentSubmitter", "documentTitleText" })
@XmlRootElement(name = "Correspondence")
public class CorrespondenceType extends ResourceType {

  @XmlElement(name = "CorrespondenceRecipient")
  protected List<RecipientType> correspondenceRecipient;

  @XmlElement(name = "DocumentCategoryID",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected String documentCategoryID;

  @XmlElement(name = "DocumentCategoryName",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType documentCategoryName;

  @XmlElement(name = "DocumentContent")
  protected CorrespondenceContentType documentContent;

  @XmlElement(name = "DocumentIdentification",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected IdentificationType documentIdentification;

  @XmlElement(name = "DocumentIssuanceLocation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LocationType documentIssuanceLocation;

  @XmlElement(name = "DocumentIssueDate",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected DateType documentIssueDate;

  @XmlElement(name = "DocumentLanguage",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LanguageType documentLanguage;

  @XmlElement(name = "DocumentSource",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected EntityType documentSource;

  @XmlElement(name = "DocumentStatus",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected StatusType documentStatus;

  @XmlElement(name = "DocumentSubjectText",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType documentSubjectText;

  @XmlElement(name = "DocumentSubmitter",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected EntityType documentSubmitter;

  @XmlElement(name = "DocumentTitleText",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType documentTitleText;

  /**
   * Gets the value of the correspondenceRecipient property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * correspondenceRecipient property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getCorrespondenceRecipient().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link RecipientType }
   *
   *
   */
  public List<RecipientType> getCorrespondenceRecipient() {

    if (correspondenceRecipient == null) {
      correspondenceRecipient = new ArrayList<RecipientType>();
    }
    return this.correspondenceRecipient;
  }

  /**
   * Gets the value of the documentCategoryID property.
   *
   * @return
   * possible object is
   * {@link String }
   *
   */
  public String getDocumentCategoryID() {

    return documentCategoryID;
  }

  /**
   * Sets the value of the documentCategoryID property.
   *
   * @param value
   * allowed object is
   * {@link String }
   *
   */
  public void setDocumentCategoryID(final String value) {

    this.documentCategoryID = value;
  }

  /**
   * Gets the value of the documentCategoryName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getDocumentCategoryName() {

    return documentCategoryName;
  }

  /**
   * Sets the value of the documentCategoryName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setDocumentCategoryName(final TextType value) {

    this.documentCategoryName = value;
  }

  /**
   * Gets the value of the documentContent property.
   *
   * @return
   * possible object is
   * {@link CorrespondenceContentType }
   *
   */
  public CorrespondenceContentType getDocumentContent() {

    return documentContent;
  }

  /**
   * Sets the value of the documentContent property.
   *
   * @param value
   * allowed object is
   * {@link CorrespondenceContentType }
   *
   */
  public void setDocumentContent(final CorrespondenceContentType value) {

    this.documentContent = value;
  }

  /**
   * Gets the value of the documentIdentification property.
   *
   * @return
   * possible object is
   * {@link IdentificationType }
   *
   */
  public IdentificationType getDocumentIdentification() {

    return documentIdentification;
  }

  /**
   * Sets the value of the documentIdentification property.
   *
   * @param value
   * allowed object is
   * {@link IdentificationType }
   *
   */
  public void setDocumentIdentification(final IdentificationType value) {

    this.documentIdentification = value;
  }

  /**
   * Gets the value of the documentIssuanceLocation property.
   *
   * @return
   * possible object is
   * {@link LocationType }
   *
   */
  public LocationType getDocumentIssuanceLocation() {

    return documentIssuanceLocation;
  }

  /**
   * Sets the value of the documentIssuanceLocation property.
   *
   * @param value
   * allowed object is
   * {@link LocationType }
   *
   */
  public void setDocumentIssuanceLocation(final LocationType value) {

    this.documentIssuanceLocation = value;
  }

  /**
   * Gets the value of the documentIssueDate property.
   *
   * @return
   * possible object is
   * {@link DateType }
   *
   */
  public DateType getDocumentIssueDate() {

    return documentIssueDate;
  }

  /**
   * Sets the value of the documentIssueDate property.
   *
   * @param value
   * allowed object is
   * {@link DateType }
   *
   */
  public void setDocumentIssueDate(final DateType value) {

    this.documentIssueDate = value;
  }

  /**
   * Gets the value of the documentLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getDocumentLanguage() {

    return documentLanguage;
  }

  /**
   * Sets the value of the documentLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setDocumentLanguage(final LanguageType value) {

    this.documentLanguage = value;
  }

  /**
   * Gets the value of the documentSource property.
   *
   * @return
   * possible object is
   * {@link EntityType }
   *
   */
  public EntityType getDocumentSource() {

    return documentSource;
  }

  /**
   * Sets the value of the documentSource property.
   *
   * @param value
   * allowed object is
   * {@link EntityType }
   *
   */
  public void setDocumentSource(final EntityType value) {

    this.documentSource = value;
  }

  /**
   * Gets the value of the documentStatus property.
   *
   * @return
   * possible object is
   * {@link StatusType }
   *
   */
  public StatusType getDocumentStatus() {

    return documentStatus;
  }

  /**
   * Sets the value of the documentStatus property.
   *
   * @param value
   * allowed object is
   * {@link StatusType }
   *
   */
  public void setDocumentStatus(final StatusType value) {

    this.documentStatus = value;
  }

  /**
   * Gets the value of the documentSubjectText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getDocumentSubjectText() {

    return documentSubjectText;
  }

  /**
   * Sets the value of the documentSubjectText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setDocumentSubjectText(final TextType value) {

    this.documentSubjectText = value;
  }

  /**
   * Gets the value of the documentSubmitter property.
   *
   * @return
   * possible object is
   * {@link EntityType }
   *
   */
  public EntityType getDocumentSubmitter() {

    return documentSubmitter;
  }

  /**
   * Sets the value of the documentSubmitter property.
   *
   * @param value
   * allowed object is
   * {@link EntityType }
   *
   */
  public void setDocumentSubmitter(final EntityType value) {

    this.documentSubmitter = value;
  }

  /**
   * Gets the value of the documentTitleText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getDocumentTitleText() {

    return documentTitleText;
  }

  /**
   * Sets the value of the documentTitleText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setDocumentTitleText(final TextType value) {

    this.documentTitleText = value;
  }

}
