//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a calendar date.
 *
 * <p>
 * Java class for DateType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="DateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}Date" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DateTime" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DayDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}MonthDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}YearDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"date", "dateTime", "dayDate", "monthDate", "yearDate" })
public class DateType extends ObjectType {

  @XmlElement(name = "Date", nillable = true)
  protected List<Date> date;

  @XmlElement(name = "DateTime", nillable = true)
  protected List<DateTime> dateTime;

  @XmlElement(name = "DayDate", nillable = true)
  protected List<GDay> dayDate;

  @XmlElement(name = "MonthDate", nillable = true)
  protected List<GMonth> monthDate;

  @XmlElement(name = "YearDate", nillable = true)
  protected List<GYear> yearDate;

  /**
   * Gets the value of the date property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the date property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Date }
   *
   *
   */
  public List<Date> getDate() {

    if (date == null) {
      date = new ArrayList<Date>();
    }
    return this.date;
  }

  /**
   * Gets the value of the dateTime property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the dateTime
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getDateTime().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link DateTime }
   *
   *
   */
  public List<DateTime> getDateTime() {

    if (dateTime == null) {
      dateTime = new ArrayList<DateTime>();
    }
    return this.dateTime;
  }

  /**
   * Gets the value of the dayDate property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the dayDate
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getDayDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link GDay }
   *
   *
   */
  public List<GDay> getDayDate() {

    if (dayDate == null) {
      dayDate = new ArrayList<GDay>();
    }
    return this.dayDate;
  }

  /**
   * Gets the value of the monthDate property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the monthDate
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getMonthDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link GMonth }
   *
   *
   */
  public List<GMonth> getMonthDate() {

    if (monthDate == null) {
      monthDate = new ArrayList<GMonth>();
    }
    return this.monthDate;
  }

  /**
   * Gets the value of the yearDate property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the yearDate
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getYearDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link GYear }
   *
   *
   */
  public List<GYear> getYearDate() {

    if (yearDate == null) {
      yearDate = new ArrayList<GYear>();
    }
    return this.yearDate;
  }

}
