//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a person, organization, or item.
 *
 * <p>
 * Java class for EntityType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="EntityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}EntityOrganization" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}EntityPerson" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"entityOrganization", "entityPerson" })
public class EntityType extends ObjectType {

  @XmlElement(name = "EntityOrganization", nillable = true)
  protected List<OrganizationType> entityOrganization;

  @XmlElement(name = "EntityPerson", nillable = true)
  protected List<PersonType> entityPerson;

  /**
   * Gets the value of the entityOrganization property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * entityOrganization property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getEntityOrganization().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link OrganizationType }
   *
   *
   */
  public List<OrganizationType> getEntityOrganization() {

    if (entityOrganization == null) {
      entityOrganization = new ArrayList<OrganizationType>();
    }
    return this.entityOrganization;
  }

  /**
   * Gets the value of the entityPerson property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the entityPerson
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getEntityPerson().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link PersonType }
   *
   *
   */
  public List<PersonType> getEntityPerson() {

    if (entityPerson == null) {
      entityPerson = new ArrayList<PersonType>();
    }
    return this.entityPerson;
  }

}
