//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * A data type that is patterned after the IEEE single-precision 32-bit floating
 * point type [IEEE 754-1985]. The basic value space of float consists of the
 * values m x 2^e, where m is an integer whose absolute value is less than 2^24,
 * and e is an integer between -149 and 104, inclusive. In addition to the basic
 * value space described above, the value space of float also contains the
 * following three special values: positive and negative infinity and
 * not-a-number (NaN).
 *
 * <p>
 * Java class for float complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="float"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
 *       &lt;attGroup ref="{http://release.niem.gov/niem/structures/5.0/}SimpleObjectAttributeGroup"/&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "float", propOrder = {"value" })
public class Float {

  @XmlValue
  protected float value;

  @XmlAttribute(name = "id",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected java.lang.String id;

  @XmlAttribute(name = "ref",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object ref;

  @XmlAttribute(name = "uri",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlSchemaType(name = "anyURI")
  protected java.lang.String uri;

  @XmlAttribute(name = "sequenceID",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlSchemaType(name = "positiveInteger")
  protected BigInteger sequenceID;

  @XmlAnyAttribute
  private final Map<QName, java.lang.String> otherAttributes =
    new HashMap<QName, java.lang.String>();

  /**
   * Gets the value of the value property.
   *
   */
  public float getValue() {

    return value;
  }

  /**
   * Sets the value of the value property.
   *
   */
  public void setValue(final float value) {

    this.value = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return
   * possible object is
   * {@link java.lang.String }
   *
   */
  public java.lang.String getId() {

    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.String }
   *
   */
  public void setId(final java.lang.String value) {

    this.id = value;
  }

  /**
   * Gets the value of the ref property.
   *
   * @return
   * possible object is
   * {@link Object }
   *
   */
  public Object getRef() {

    return ref;
  }

  /**
   * Sets the value of the ref property.
   *
   * @param value
   * allowed object is
   * {@link Object }
   *
   */
  public void setRef(final Object value) {

    this.ref = value;
  }

  /**
   * Gets the value of the uri property.
   *
   * @return
   * possible object is
   * {@link java.lang.String }
   *
   */
  public java.lang.String getUri() {

    return uri;
  }

  /**
   * Sets the value of the uri property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.String }
   *
   */
  public void setUri(final java.lang.String value) {

    this.uri = value;
  }

  /**
   * Gets the value of the sequenceID property.
   *
   * @return
   * possible object is
   * {@link BigInteger }
   *
   */
  public BigInteger getSequenceID() {

    return sequenceID;
  }

  /**
   * Sets the value of the sequenceID property.
   *
   * @param value
   * allowed object is
   * {@link BigInteger }
   *
   */
  public void setSequenceID(final BigInteger value) {

    this.sequenceID = value;
  }

  /**
   * Gets a map that contains attributes that aren't bound to any typed property
   * on this class.
   *
   * <p>
   * the map is keyed by the name of the attribute and
   * the value is the string value of the attribute.
   *
   * the map returned by this method is live, and you can add new attribute
   * by updating the map directly. Because of this design, there's no setter.
   *
   *
   * @return
   * always non-null
   */
  public Map<QName, java.lang.String> getOtherAttributes() {

    return otherAttributes;
  }

}
