//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for geospatial location.
 *
 * <p>
 * Java class for LocationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="LocationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}Address" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationCategoryText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationContactInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"address", "locationCategoryText",
    "locationContactInformation", "locationDescriptionText",
    "locationIdentification", "locationName" })
public class LocationType extends ObjectType {

  @XmlElement(name = "Address", nillable = true)
  protected List<AddressType> address;

  @XmlElement(name = "LocationCategoryText", nillable = true)
  protected List<TextType> locationCategoryText;

  @XmlElement(name = "LocationContactInformation", nillable = true)
  protected List<ContactInformationType> locationContactInformation;

  @XmlElement(name = "LocationDescriptionText", nillable = true)
  protected List<TextType> locationDescriptionText;

  @XmlElement(name = "LocationIdentification", nillable = true)
  protected List<IdentificationType> locationIdentification;

  @XmlElement(name = "LocationName", nillable = true)
  protected List<TextType> locationName;

  /**
   * Gets the value of the address property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the address
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getAddress().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link AddressType }
   *
   *
   */
  public List<AddressType> getAddress() {

    if (address == null) {
      address = new ArrayList<AddressType>();
    }
    return this.address;
  }

  /**
   * Gets the value of the locationCategoryText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * locationCategoryText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getLocationCategoryText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getLocationCategoryText() {

    if (locationCategoryText == null) {
      locationCategoryText = new ArrayList<TextType>();
    }
    return this.locationCategoryText;
  }

  /**
   * Gets the value of the locationContactInformation property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * locationContactInformation property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getLocationContactInformation().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ContactInformationType }
   *
   *
   */
  public List<ContactInformationType> getLocationContactInformation() {

    if (locationContactInformation == null) {
      locationContactInformation = new ArrayList<ContactInformationType>();
    }
    return this.locationContactInformation;
  }

  /**
   * Gets the value of the locationDescriptionText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * locationDescriptionText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getLocationDescriptionText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getLocationDescriptionText() {

    if (locationDescriptionText == null) {
      locationDescriptionText = new ArrayList<TextType>();
    }
    return this.locationDescriptionText;
  }

  /**
   * Gets the value of the locationIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * locationIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getLocationIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getLocationIdentification() {

    if (locationIdentification == null) {
      locationIdentification = new ArrayList<IdentificationType>();
    }
    return this.locationIdentification;
  }

  /**
   * Gets the value of the locationName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the locationName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getLocationName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getLocationName() {

    if (locationName == null) {
      locationName = new ArrayList<TextType>();
    }
    return this.locationName;
  }

}
