//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * A data type for a thing with its own lifespan that has some existence.
 *
 * <p>
 * Java class for ObjectType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ObjectType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/structures/5.0/}ObjectAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://release.niem.gov/niem/structures/5.0/}id"/&gt;
 *       &lt;attribute ref="{http://release.niem.gov/niem/structures/5.0/}ref"/&gt;
 *       &lt;attribute ref="{http://release.niem.gov/niem/structures/5.0/}uri"/&gt;
 *       &lt;attribute ref="{http://release.niem.gov/niem/structures/5.0/}sequenceID"/&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectType",
  namespace = "http://release.niem.gov/niem/structures/5.0/",
  propOrder = {"objectAugmentationPoint" })
@XmlSeeAlso({CountryType.class, DateType.class, IdentificationType.class,
  ProvinceType.class, StatusType.class, RecipientType.class,
  CorrespondenceContentType.class, LanguageType.class, AddressType.class,
  ResourceType.class, StreetType.class, TelephoneNumberType.class,
  LocationType.class, EntityType.class, OrganizationType.class,
  PersonType.class, FullTelephoneNumberType.class,
  ContactInformationType.class, PersonNameType.class })
public abstract class ObjectType {

  @XmlElement(name = "ObjectAugmentationPoint")
  protected List<Object> objectAugmentationPoint;

  @XmlAttribute(name = "id",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected java.lang.String id;

  @XmlAttribute(name = "ref",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object ref;

  @XmlAttribute(name = "uri",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlSchemaType(name = "anyURI")
  protected java.lang.String uri;

  @XmlAttribute(name = "sequenceID",
    namespace = "http://release.niem.gov/niem/structures/5.0/")
  @XmlSchemaType(name = "positiveInteger")
  protected BigInteger sequenceID;

  @XmlAnyAttribute
  private final Map<QName, java.lang.String> otherAttributes =
    new HashMap<QName, java.lang.String>();

  /**
   * Gets the value of the objectAugmentationPoint property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * objectAugmentationPoint property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getObjectAugmentationPoint().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Object }
   *
   *
   */
  public List<Object> getObjectAugmentationPoint() {

    if (objectAugmentationPoint == null) {
      objectAugmentationPoint = new ArrayList<Object>();
    }
    return this.objectAugmentationPoint;
  }

  /**
   * Gets the value of the id property.
   *
   * @return
   * possible object is
   * {@link java.lang.String }
   *
   */
  public java.lang.String getId() {

    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.String }
   *
   */
  public void setId(final java.lang.String value) {

    this.id = value;
  }

  /**
   * Gets the value of the ref property.
   *
   * @return
   * possible object is
   * {@link Object }
   *
   */
  public Object getRef() {

    return ref;
  }

  /**
   * Sets the value of the ref property.
   *
   * @param value
   * allowed object is
   * {@link Object }
   *
   */
  public void setRef(final Object value) {

    this.ref = value;
  }

  /**
   * Gets the value of the uri property.
   *
   * @return
   * possible object is
   * {@link java.lang.String }
   *
   */
  public java.lang.String getUri() {

    return uri;
  }

  /**
   * Sets the value of the uri property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.String }
   *
   */
  public void setUri(final java.lang.String value) {

    this.uri = value;
  }

  /**
   * Gets the value of the sequenceID property.
   *
   * @return
   * possible object is
   * {@link BigInteger }
   *
   */
  public BigInteger getSequenceID() {

    return sequenceID;
  }

  /**
   * Sets the value of the sequenceID property.
   *
   * @param value
   * allowed object is
   * {@link BigInteger }
   *
   */
  public void setSequenceID(final BigInteger value) {

    this.sequenceID = value;
  }

  /**
   * Gets a map that contains attributes that aren't bound to any typed property
   * on this class.
   *
   * <p>
   * the map is keyed by the name of the attribute and
   * the value is the string value of the attribute.
   *
   * the map returned by this method is live, and you can add new attribute
   * by updating the map directly. Because of this design, there's no setter.
   *
   *
   * @return
   * always non-null
   */
  public Map<QName, java.lang.String> getOtherAttributes() {

    return otherAttributes;
  }

}
