//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a body of people organized for a particular purpose.
 *
 * <p>
 * Java class for OrganizationType1 complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="OrganizationType1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}OrganizationCategoryText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}OrganizationDescriptionText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}OrganizationIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}OrganizationLocation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}OrganizationName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationType1",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"organizationCategoryText", "organizationDescriptionText",
    "organizationIdentification", "organizationLocation",
    "organizationName" })
public class OrganizationType1 extends ResourceType {

  @XmlElement(name = "OrganizationCategoryText",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType organizationCategoryText;

  @XmlElement(name = "OrganizationDescriptionText",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType organizationDescriptionText;

  @XmlElement(name = "OrganizationIdentification",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected List<IdentificationType> organizationIdentification;

  @XmlElement(name = "OrganizationLocation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LocationType organizationLocation;

  @XmlElement(name = "OrganizationName",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType organizationName;

  /**
   * Gets the value of the organizationCategoryText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getOrganizationCategoryText() {

    return organizationCategoryText;
  }

  /**
   * Sets the value of the organizationCategoryText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setOrganizationCategoryText(final TextType value) {

    this.organizationCategoryText = value;
  }

  /**
   * Gets the value of the organizationDescriptionText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getOrganizationDescriptionText() {

    return organizationDescriptionText;
  }

  /**
   * Sets the value of the organizationDescriptionText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setOrganizationDescriptionText(final TextType value) {

    this.organizationDescriptionText = value;
  }

  /**
   * Gets the value of the organizationIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * organizationIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getOrganizationIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getOrganizationIdentification() {

    if (organizationIdentification == null) {
      organizationIdentification = new ArrayList<IdentificationType>();
    }
    return this.organizationIdentification;
  }

  /**
   * Gets the value of the organizationLocation property.
   *
   * @return
   * possible object is
   * {@link LocationType }
   *
   */
  public LocationType getOrganizationLocation() {

    return organizationLocation;
  }

  /**
   * Sets the value of the organizationLocation property.
   *
   * @param value
   * allowed object is
   * {@link LocationType }
   *
   */
  public void setOrganizationLocation(final LocationType value) {

    this.organizationLocation = value;
  }

  /**
   * Gets the value of the organizationName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getOrganizationName() {

    return organizationName;
  }

  /**
   * Sets the value of the organizationName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setOrganizationName(final TextType value) {

    this.organizationName = value;
  }

}
