//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.09.27 at 09:41:07 AM EDT
//

// @javax.xml.bind.annotation.XmlSchema(
// namespace = "http://release.niem.gov/niem/proxy/niem-xs/5.0/",
// elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

@javax.xml.bind.annotation.XmlSchema(xmlns = {
  @javax.xml.bind.annotation.XmlNs(prefix = "sp",
    namespaceURI = "http://interoperability.gc.ca/socialprogram/1.0/"),
  @javax.xml.bind.annotation.XmlNs(prefix = "nc",
    namespaceURI = "http://release.niem.gov/niem/niem-core/5.0/"),
  @javax.xml.bind.annotation.XmlNs(prefix = "niem-xs",
    namespaceURI = "http://release.niem.gov/niem/proxy/niem-xs/5.0/"),
  @javax.xml.bind.annotation.XmlNs(prefix = "cli",
    namespaceURI = "http://reference.niem.gov/niem/specification/code-lists/5.0/code-lists-instance/"),
  @javax.xml.bind.annotation.XmlNs(prefix = "structures",
    namespaceURI = "http://release.niem.gov/niem/structures/5.0/") },
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
  attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;
