//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a human being.
 *
 * <p>
 * Java class for PersonType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PersonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonBirthDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonBirthLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonDeathDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonHumanResourceIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonPrimaryLanguage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonSecondaryLanguage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonSexText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonContactInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"personBirthDate", "personBirthLocation", "personDeathDate",
    "personHumanResourceIdentification", "personName",
    "personPrimaryLanguage", "personSecondaryLanguage", "personSexText",
    "personContactInformation" })
public class PersonType extends ObjectType {

  @XmlElement(name = "PersonBirthDate", nillable = true)
  protected List<DateType> personBirthDate;

  @XmlElement(name = "PersonBirthLocation", nillable = true)
  protected List<LocationType> personBirthLocation;

  @XmlElement(name = "PersonDeathDate", nillable = true)
  protected List<DateType> personDeathDate;

  @XmlElement(name = "PersonHumanResourceIdentification", nillable = true)
  protected List<IdentificationType> personHumanResourceIdentification;

  @XmlElement(name = "PersonName", nillable = true)
  protected List<PersonNameType> personName;

  @XmlElement(name = "PersonPrimaryLanguage", nillable = true)
  protected List<LanguageType> personPrimaryLanguage;

  @XmlElement(name = "PersonSecondaryLanguage", nillable = true)
  protected List<LanguageType> personSecondaryLanguage;

  @XmlElement(name = "PersonSexText", nillable = true)
  protected List<TextType> personSexText;

  @XmlElement(name = "PersonContactInformation", nillable = true)
  protected List<ContactInformationType> personContactInformation;

  /**
   * Gets the value of the personBirthDate property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personBirthDate
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonBirthDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link DateType }
   *
   *
   */
  public List<DateType> getPersonBirthDate() {

    if (personBirthDate == null) {
      personBirthDate = new ArrayList<DateType>();
    }
    return this.personBirthDate;
  }

  /**
   * Gets the value of the personBirthLocation property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personBirthLocation property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonBirthLocation().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link LocationType }
   *
   *
   */
  public List<LocationType> getPersonBirthLocation() {

    if (personBirthLocation == null) {
      personBirthLocation = new ArrayList<LocationType>();
    }
    return this.personBirthLocation;
  }

  /**
   * Gets the value of the personDeathDate property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personDeathDate
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonDeathDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link DateType }
   *
   *
   */
  public List<DateType> getPersonDeathDate() {

    if (personDeathDate == null) {
      personDeathDate = new ArrayList<DateType>();
    }
    return this.personDeathDate;
  }

  /**
   * Gets the value of the personHumanResourceIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personHumanResourceIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonHumanResourceIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getPersonHumanResourceIdentification() {

    if (personHumanResourceIdentification == null) {
      personHumanResourceIdentification = new ArrayList<IdentificationType>();
    }
    return this.personHumanResourceIdentification;
  }

  /**
   * Gets the value of the personName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link PersonNameType }
   *
   *
   */
  public List<PersonNameType> getPersonName() {

    if (personName == null) {
      personName = new ArrayList<PersonNameType>();
    }
    return this.personName;
  }

  /**
   * Gets the value of the personPrimaryLanguage property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personPrimaryLanguage property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonPrimaryLanguage().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link LanguageType }
   *
   *
   */
  public List<LanguageType> getPersonPrimaryLanguage() {

    if (personPrimaryLanguage == null) {
      personPrimaryLanguage = new ArrayList<LanguageType>();
    }
    return this.personPrimaryLanguage;
  }

  /**
   * Gets the value of the personSecondaryLanguage property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personSecondaryLanguage property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonSecondaryLanguage().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link LanguageType }
   *
   *
   */
  public List<LanguageType> getPersonSecondaryLanguage() {

    if (personSecondaryLanguage == null) {
      personSecondaryLanguage = new ArrayList<LanguageType>();
    }
    return this.personSecondaryLanguage;
  }

  /**
   * Gets the value of the personSexText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personSexText
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonSexText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonSexText() {

    if (personSexText == null) {
      personSexText = new ArrayList<TextType>();
    }
    return this.personSexText;
  }

  /**
   * Gets the value of the personContactInformation property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personContactInformation property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonContactInformation().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ContactInformationType }
   *
   *
   */
  public List<ContactInformationType> getPersonContactInformation() {

    if (personContactInformation == null) {
      personContactInformation = new ArrayList<ContactInformationType>();
    }
    return this.personContactInformation;
  }

}
