//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a combination of names and/or titles by which a person is
 * known.
 *
 * <p>
 * Java class for PersonNameType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PersonNameType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonGivenName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonMiddleName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonSurName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonMaidenName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonFullName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonNameCategoryText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonNameType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"personGivenName", "personMiddleName", "personSurName",
    "personMaidenName", "personFullName", "personNameCategoryText" })
public class PersonNameType extends ObjectType {

  @XmlElement(name = "PersonGivenName", nillable = true)
  protected List<TextType> personGivenName;

  @XmlElement(name = "PersonMiddleName", nillable = true)
  protected List<TextType> personMiddleName;

  @XmlElement(name = "PersonSurName", nillable = true)
  protected List<TextType> personSurName;

  @XmlElement(name = "PersonMaidenName", nillable = true)
  protected List<TextType> personMaidenName;

  @XmlElement(name = "PersonFullName", nillable = true)
  protected List<TextType> personFullName;

  @XmlElement(name = "PersonNameCategoryText", nillable = true)
  protected List<TextType> personNameCategoryText;

  /**
   * Gets the value of the personGivenName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personGivenName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonGivenName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonGivenName() {

    if (personGivenName == null) {
      personGivenName = new ArrayList<TextType>();
    }
    return this.personGivenName;
  }

  /**
   * Gets the value of the personMiddleName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personMiddleName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonMiddleName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonMiddleName() {

    if (personMiddleName == null) {
      personMiddleName = new ArrayList<TextType>();
    }
    return this.personMiddleName;
  }

  /**
   * Gets the value of the personSurName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personSurName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonSurName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonSurName() {

    if (personSurName == null) {
      personSurName = new ArrayList<TextType>();
    }
    return this.personSurName;
  }

  /**
   * Gets the value of the personMaidenName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personMaidenName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonMaidenName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonMaidenName() {

    if (personMaidenName == null) {
      personMaidenName = new ArrayList<TextType>();
    }
    return this.personMaidenName;
  }

  /**
   * Gets the value of the personFullName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personFullName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonFullName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonFullName() {

    if (personFullName == null) {
      personFullName = new ArrayList<TextType>();
    }
    return this.personFullName;
  }

  /**
   * Gets the value of the personNameCategoryText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personNameCategoryText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonNameCategoryText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getPersonNameCategoryText() {

    if (personNameCategoryText == null) {
      personNameCategoryText = new ArrayList<TextType>();
    }
    return this.personNameCategoryText;
  }

}
