//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Information about a program administered by or on behalf of any governmental
 * authority.
 *
 * <p>
 * Java class for ProgramType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ProgramType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ProgramAbbreviationText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ProgramDescriptionText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ProgramIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ProgramName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProgramType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"programAbbreviationText", "programDescriptionText",
    "programIdentification", "programName" })
public class ProgramType extends ResourceType {

  @XmlElement(name = "ProgramAbbreviationText")
  protected TextType programAbbreviationText;

  @XmlElement(name = "ProgramDescriptionText")
  protected TextType programDescriptionText;

  @XmlElement(name = "ProgramIdentification")
  protected List<IdentificationType> programIdentification;

  @XmlElement(name = "ProgramName")
  protected TextType programName;

  /**
   * Gets the value of the programAbbreviationText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getProgramAbbreviationText() {

    return programAbbreviationText;
  }

  /**
   * Sets the value of the programAbbreviationText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setProgramAbbreviationText(final TextType value) {

    this.programAbbreviationText = value;
  }

  /**
   * Gets the value of the programDescriptionText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getProgramDescriptionText() {

    return programDescriptionText;
  }

  /**
   * Sets the value of the programDescriptionText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setProgramDescriptionText(final TextType value) {

    this.programDescriptionText = value;
  }

  /**
   * Gets the value of the programIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * programIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getProgramIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getProgramIdentification() {

    if (programIdentification == null) {
      programIdentification = new ArrayList<IdentificationType>();
    }
    return this.programIdentification;
  }

  /**
   * Gets the value of the programName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getProgramName() {

    return programName;
  }

  /**
   * Sets the value of the programName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setProgramName(final TextType value) {

    this.programName = value;
  }

}
