//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a province of a country.
 *
 * <p>
 * Java class for ProvinceType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ProvinceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ProvinceCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ProvinceName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProvinceType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"provinceCode", "provinceName" })
public class ProvinceType extends ObjectType {

  @XmlElement(name = "ProvinceCode", nillable = true)
  protected TextType provinceCode;

  @XmlElement(name = "ProvinceName", nillable = true)
  protected TextType provinceName;

  /**
   * Gets the value of the provinceCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getProvinceCode() {

    return provinceCode;
  }

  /**
   * Sets the value of the provinceCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setProvinceCode(final TextType value) {

    this.provinceCode = value;
  }

  /**
   * Gets the value of the provinceName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getProvinceName() {

    return provinceName;
  }

  /**
   * Sets the value of the provinceName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setProvinceName(final TextType value) {

    this.provinceName = value;
  }

}
