//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.28 at 11:59:40 AM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * An entity that is a target or intended recipient of a document.
 *
 * <p>
 * Java class for RecipientType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="RecipientType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RecipientAddress" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RecipientCategoryCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RecipientCategoryText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RecipientContactCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RecipientContactText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RecipientName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecipientType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"recipientAddress", "recipientCategoryCode",
    "recipientCategoryText", "recipientContactCode", "recipientContactText",
    "recipientName", "recipientPreferredLanguage" })
public class RecipientType extends ObjectType {

  @XmlElement(name = "RecipientAddress")
  protected AddressType recipientAddress;

  @XmlElement(name = "RecipientCategoryCode")
  protected TextType recipientCategoryCode;

  @XmlElement(name = "RecipientCategoryText")
  protected TextType recipientCategoryText;

  @XmlElement(name = "RecipientContactCode")
  protected TextType recipientContactCode;

  @XmlElement(name = "RecipientContactText")
  protected TextType recipientContactText;

  @XmlElement(name = "RecipientName")
  protected TextType recipientName;

  @XmlElement(name = "RecipientPreferredLanguage", nillable = true)
  protected LanguageType recipientPreferredLanguage;

  /**
   * Gets the value of the recipientAddress property.
   *
   * @return
   * possible object is
   * {@link AddressType }
   *
   */
  public AddressType getRecipientAddress() {

    return recipientAddress;
  }

  /**
   * Sets the value of the recipientAddress property.
   *
   * @param value
   * allowed object is
   * {@link AddressType }
   *
   */
  public void setRecipientAddress(final AddressType value) {

    this.recipientAddress = value;
  }

  /**
   * Gets the value of the recipientCategoryCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getRecipientCategoryCode() {

    return recipientCategoryCode;
  }

  /**
   * Sets the value of the recipientCategoryCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setRecipientCategoryCode(final TextType value) {

    this.recipientCategoryCode = value;
  }

  /**
   * Gets the value of the recipientCategoryText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getRecipientCategoryText() {

    return recipientCategoryText;
  }

  /**
   * Sets the value of the recipientCategoryText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setRecipientCategoryText(final TextType value) {

    this.recipientCategoryText = value;
  }

  /**
   * Gets the value of the recipientContactCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getRecipientContactCode() {

    return recipientContactCode;
  }

  /**
   * Sets the value of the recipientContactCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setRecipientContactCode(final TextType value) {

    this.recipientContactCode = value;
  }

  /**
   * Gets the value of the recipientContactText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getRecipientContactText() {

    return recipientContactText;
  }

  /**
   * Sets the value of the recipientContactText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setRecipientContactText(final TextType value) {

    this.recipientContactText = value;
  }

  /**
   * Gets the value of the recipientName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getRecipientName() {

    return recipientName;
  }

  /**
   * Sets the value of the recipientName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setRecipientName(final TextType value) {

    this.recipientName = value;
  }

  /**
   * Gets the value of the personPreferredLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getRecipientPreferredLanguage() {

    return recipientPreferredLanguage;
  }

  /**
   * Sets the value of the personPreferredLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setRecipientPreferredLanguage(final LanguageType value) {

    this.recipientPreferredLanguage = value;
  }

}
