//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for the relatedPerson resource.
 *
 * <p>
 * Java class for RelatedPersonType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="RelatedPersonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonContactInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonBirthDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonBirthLocation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonPrimaryLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}PersonSecondaryLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}PersonRelationshipCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}PersonSINIdentification" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}RelatedPersonIdentification" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedPersonType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"personName", "personContactInformation", "personBirthDate",
    "personBirthLocation", "personPrimaryLanguage", "personSecondaryLanguage",
    "personRelationshipCode", "personSINIdentification",
    "relatedPersonIdentification" })
public class RelatedPersonType extends ResourceType {

  @XmlElement(name = "PersonName",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected List<PersonNameType> personName;

  @XmlElement(name = "PersonContactInformation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected List<ContactInformationType> personContactInformation;

  @XmlElement(name = "PersonBirthDate",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected DateType personBirthDate;

  @XmlElement(name = "PersonBirthLocation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LocationType personBirthLocation;

  @XmlElement(name = "PersonPrimaryLanguage",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LanguageType personPrimaryLanguage;

  @XmlElement(name = "PersonSecondaryLanguage",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected LanguageType personSecondaryLanguage;

  @XmlElement(name = "PersonRelationshipCode", nillable = true)
  protected TextType personRelationshipCode;

  @XmlElement(name = "PersonSINIdentification", nillable = true)
  protected IdentificationType personSINIdentification;

  @XmlElement(name = "RelatedPersonIdentification", nillable = true)
  protected IdentificationType relatedPersonIdentification;

  /**
   * Gets the value of the personName property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the personName
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonName().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link PersonNameType }
   *
   *
   */
  public List<PersonNameType> getPersonName() {

    if (personName == null) {
      personName = new ArrayList<PersonNameType>();
    }
    return this.personName;
  }

  /**
   * Gets the value of the personContactInformation property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * personContactInformation property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getPersonContactInformation().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ContactInformationType }
   *
   *
   */
  public List<ContactInformationType> getPersonContactInformation() {

    if (personContactInformation == null) {
      personContactInformation = new ArrayList<ContactInformationType>();
    }
    return this.personContactInformation;
  }

  /**
   * Gets the value of the personBirthDate property.
   *
   * @return
   * possible object is
   * {@link DateType }
   *
   */
  public DateType getPersonBirthDate() {

    return personBirthDate;
  }

  /**
   * Sets the value of the personBirthDate property.
   *
   * @param value
   * allowed object is
   * {@link DateType }
   *
   */
  public void setPersonBirthDate(final DateType value) {

    this.personBirthDate = value;
  }

  /**
   * Gets the value of the personBirthLocation property.
   *
   * @return
   * possible object is
   * {@link LocationType }
   *
   */
  public LocationType getPersonBirthLocation() {

    return personBirthLocation;
  }

  /**
   * Sets the value of the personBirthLocation property.
   *
   * @param value
   * allowed object is
   * {@link LocationType }
   *
   */
  public void setPersonBirthLocation(final LocationType value) {

    this.personBirthLocation = value;
  }

  /**
   * Gets the value of the personPrimaryLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getPersonPrimaryLanguage() {

    return personPrimaryLanguage;
  }

  /**
   * Sets the value of the personPrimaryLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setPersonPrimaryLanguage(final LanguageType value) {

    this.personPrimaryLanguage = value;
  }

  /**
   * Gets the value of the personSecondaryLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getPersonSecondaryLanguage() {

    return personSecondaryLanguage;
  }

  /**
   * Sets the value of the personSecondaryLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setPersonSecondaryLanguage(final LanguageType value) {

    this.personSecondaryLanguage = value;
  }

  /**
   * Gets the value of the personRelationshipCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getPersonRelationshipCode() {

    return personRelationshipCode;
  }

  /**
   * Sets the value of the personRelationshipCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setPersonRelationshipCode(final TextType value) {

    this.personRelationshipCode = value;
  }

  /**
   * Gets the value of the personSINIdentification property.
   *
   * @return
   * possible object is
   * {@link IdentificationType }
   *
   */
  public IdentificationType getPersonSINIdentification() {

    return personSINIdentification;
  }

  /**
   * Sets the value of the personSINIdentification property.
   *
   * @param value
   * allowed object is
   * {@link IdentificationType }
   *
   */
  public void setPersonSINIdentification(final IdentificationType value) {

    this.personSINIdentification = value;
  }

  /**
   * Gets the value of the relatedPersonIdentification property.
   *
   * @return
   * possible object is
   * {@link IdentificationType }
   *
   */
  public IdentificationType getRelatedPersonIdentification() {

    return relatedPersonIdentification;
  }

  /**
   * Sets the value of the relatedPersonIdentification property.
   *
   * @param value
   * allowed object is
   * {@link IdentificationType }
   *
   */
  public void setRelatedPersonIdentification(final IdentificationType value) {

    this.relatedPersonIdentification = value;
  }

}
