//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a resource.
 *
 * <p>
 * Java class for ResourceType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ResourceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceID" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceLanguage" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceReference" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"resourceID", "resourceLanguage", "resourceReference" })
@XmlSeeAlso({ClientType.class, BenefitType.class,
  BenefitApplicationType.class, ProgramType.class, CorrespondenceType.class,
  OrganizationType1.class, RelatedPersonType.class, ServiceOfficeType.class })
public class ResourceType extends ObjectType {

  @XmlElement(name = "ResourceID")
  protected TextType resourceID;

  @XmlElement(name = "ResourceLanguage")
  protected LanguageType resourceLanguage;

  @XmlElement(name = "ResourceReference", nillable = true)
  protected TextType resourceReference;

  /**
   * Gets the value of the resourceID property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getResourceID() {

    return resourceID;
  }

  /**
   * Sets the value of the resourceID property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setResourceID(final TextType value) {

    this.resourceID = value;
  }

  /**
   * Gets the value of the resourceLanguage property.
   *
   * @return
   * possible object is
   * {@link LanguageType }
   *
   */
  public LanguageType getResourceLanguage() {

    return resourceLanguage;
  }

  /**
   * Sets the value of the resourceLanguage property.
   *
   * @param value
   * allowed object is
   * {@link LanguageType }
   *
   */
  public void setResourceLanguage(final LanguageType value) {

    this.resourceLanguage = value;
  }

  /**
   * Gets the value of the resourceReference property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getResourceReference() {

    return resourceReference;
  }

  /**
   * Sets the value of the resourceReference property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setResourceReference(final TextType value) {

    this.resourceReference = value;
  }

}
