//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a Service Office that provides the public with a single point
 * of access to a wide range of government services and benefits.
 *
 * <p>
 * Java class for ServiceOfficeType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ServiceOfficeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://interoperability.gc.ca/socialprogram/1.0/}ResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationContactInformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}LocationName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ServiceOfficeCategoryCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ServiceOfficeCategoryText" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ServiceOfficeCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ServiceOfficeIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://interoperability.gc.ca/socialprogram/1.0/}ServiceOfficeName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOfficeType",
  namespace = "http://interoperability.gc.ca/socialprogram/1.0/",
  propOrder = {"locationContactInformation", "locationName",
    "serviceOfficeCategoryCode", "serviceOfficeCategoryText",
    "serviceOfficeCode", "serviceOfficeIdentification", "serviceOfficeName" })
public class ServiceOfficeType extends ResourceType {

  @XmlElement(name = "LocationContactInformation",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected ContactInformationType locationContactInformation;

  @XmlElement(name = "LocationName",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/",
    nillable = true)
  protected TextType locationName;

  @XmlElement(name = "ServiceOfficeCategoryCode", nillable = true)
  protected TextType serviceOfficeCategoryCode;

  @XmlElement(name = "ServiceOfficeCategoryText", nillable = true)
  protected TextType serviceOfficeCategoryText;

  @XmlElement(name = "ServiceOfficeCode", nillable = true)
  protected TextType serviceOfficeCode;

  @XmlElement(name = "ServiceOfficeIdentification", nillable = true)
  protected List<IdentificationType> serviceOfficeIdentification;

  @XmlElement(name = "ServiceOfficeName", nillable = true)
  protected TextType serviceOfficeName;

  /**
   * Gets the value of the locationContactInformation property.
   *
   * @return
   * possible object is
   * {@link ContactInformationType }
   *
   */
  public ContactInformationType getLocationContactInformation() {

    return locationContactInformation;
  }

  /**
   * Sets the value of the locationContactInformation property.
   *
   * @param value
   * allowed object is
   * {@link ContactInformationType }
   *
   */
  public void
    setLocationContactInformation(final ContactInformationType value) {

    this.locationContactInformation = value;
  }

  /**
   * Gets the value of the locationName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getLocationName() {

    return locationName;
  }

  /**
   * Sets the value of the locationName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setLocationName(final TextType value) {

    this.locationName = value;
  }

  /**
   * Gets the value of the serviceOfficeCategoryCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getServiceOfficeCategoryCode() {

    return serviceOfficeCategoryCode;
  }

  /**
   * Sets the value of the serviceOfficeCategoryCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setServiceOfficeCategoryCode(final TextType value) {

    this.serviceOfficeCategoryCode = value;
  }

  /**
   * Gets the value of the serviceOfficeCategoryText property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getServiceOfficeCategoryText() {

    return serviceOfficeCategoryText;
  }

  /**
   * Sets the value of the serviceOfficeCategoryText property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setServiceOfficeCategoryText(final TextType value) {

    this.serviceOfficeCategoryText = value;
  }

  /**
   * Gets the value of the serviceOfficeCode property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getServiceOfficeCode() {

    return serviceOfficeCode;
  }

  /**
   * Sets the value of the serviceOfficeCode property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setServiceOfficeCode(final TextType value) {

    this.serviceOfficeCode = value;
  }

  /**
   * Gets the value of the serviceOfficeIdentification property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * serviceOfficeIdentification property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getServiceOfficeIdentification().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link IdentificationType }
   *
   *
   */
  public List<IdentificationType> getServiceOfficeIdentification() {

    if (serviceOfficeIdentification == null) {
      serviceOfficeIdentification = new ArrayList<IdentificationType>();
    }
    return this.serviceOfficeIdentification;
  }

  /**
   * Gets the value of the serviceOfficeName property.
   *
   * @return
   * possible object is
   * {@link TextType }
   *
   */
  public TextType getServiceOfficeName() {

    return serviceOfficeName;
  }

  /**
   * Sets the value of the serviceOfficeName property.
   *
   * @param value
   * allowed object is
   * {@link TextType }
   *
   */
  public void setServiceOfficeName(final TextType value) {

    this.serviceOfficeName = value;
  }

}
