//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a state of something or someone.
 *
 * <p>
 * Java class for StatusType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="StatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}StatusText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}StatusCommentText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}StatusDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}StatusDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"statusText", "statusCommentText", "statusDescriptionText",
    "statusDate" })
public class StatusType extends ObjectType {

  @XmlElement(name = "StatusText", nillable = true)
  protected List<TextType> statusText;

  @XmlElement(name = "StatusCommentText", nillable = true)
  protected List<TextType> statusCommentText;

  @XmlElement(name = "StatusDescriptionText", nillable = true)
  protected List<TextType> statusDescriptionText;

  @XmlElement(name = "StatusDate", nillable = true)
  protected List<DateType> statusDate;

  /**
   * Gets the value of the statusText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the statusText
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getStatusText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getStatusText() {

    if (statusText == null) {
      statusText = new ArrayList<TextType>();
    }
    return this.statusText;
  }

  /**
   * Gets the value of the statusCommentText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * statusCommentText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getStatusCommentText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getStatusCommentText() {

    if (statusCommentText == null) {
      statusCommentText = new ArrayList<TextType>();
    }
    return this.statusCommentText;
  }

  /**
   * Gets the value of the statusDescriptionText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * statusDescriptionText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getStatusDescriptionText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getStatusDescriptionText() {

    if (statusDescriptionText == null) {
      statusDescriptionText = new ArrayList<TextType>();
    }
    return this.statusDescriptionText;
  }

  /**
   * Gets the value of the statusDate property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the statusDate
   * property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getStatusDate().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link DateType }
   *
   *
   */
  public List<DateType> getStatusDate() {

    if (statusDate == null) {
      statusDate = new ArrayList<DateType>();
    }
    return this.statusDate;
  }

}
