//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a telephone number for a telecommunication device.
 *
 * <p>
 * Java class for TelephoneNumberType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="TelephoneNumberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}FullTelephoneNumber" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}TelephoneNumberCategoryText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}TelephoneNumberDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelephoneNumberType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/",
  propOrder = {"fullTelephoneNumber", "telephoneNumberCategoryText",
    "telephoneNumberDescriptionText" })
public class TelephoneNumberType extends ObjectType {

  @XmlElement(name = "FullTelephoneNumber", nillable = true)
  protected List<FullTelephoneNumberType> fullTelephoneNumber;

  @XmlElement(name = "TelephoneNumberCategoryText", nillable = true)
  protected List<TextType> telephoneNumberCategoryText;

  @XmlElement(name = "TelephoneNumberDescriptionText", nillable = true)
  protected List<TextType> telephoneNumberDescriptionText;

  /**
   * Gets the value of the fullTelephoneNumber property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * fullTelephoneNumber property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getFullTelephoneNumber().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link FullTelephoneNumberType }
   *
   *
   */
  public List<FullTelephoneNumberType> getFullTelephoneNumber() {

    if (fullTelephoneNumber == null) {
      fullTelephoneNumber = new ArrayList<FullTelephoneNumberType>();
    }
    return this.fullTelephoneNumber;
  }

  /**
   * Gets the value of the telephoneNumberCategoryText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * telephoneNumberCategoryText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getTelephoneNumberCategoryText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getTelephoneNumberCategoryText() {

    if (telephoneNumberCategoryText == null) {
      telephoneNumberCategoryText = new ArrayList<TextType>();
    }
    return this.telephoneNumberCategoryText;
  }

  /**
   * Gets the value of the telephoneNumberDescriptionText property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the Jakarta XML Binding object.
   * This is why there is not a <CODE>set</CODE> method for the
   * telephoneNumberDescriptionText property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getTelephoneNumberDescriptionText().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   *
   *
   */
  public List<TextType> getTelephoneNumberDescriptionText() {

    if (telephoneNumberDescriptionText == null) {
      telephoneNumberDescriptionText = new ArrayList<TextType>();
    }
    return this.telephoneNumberDescriptionText;
  }

}
