//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2022.10.17 at 01:30:31 PM EDT
//

package curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * A data type for a character string.
 *
 * <p>
 * Java class for TextType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="TextType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://release.niem.gov/niem/proxy/niem-xs/5.0/&gt;string"&gt;
 *       &lt;attribute ref="{http://release.niem.gov/niem/niem-core/5.0/}partialIndicator"/&gt;
 *       &lt;attribute ref="{http://release.niem.gov/niem/niem-core/5.0/}truncationIndicator"/&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType",
  namespace = "http://release.niem.gov/niem/niem-core/5.0/")
public class TextType
  extends curam.ca.gc.bdm.rest.bdmcorrespondenceapi.jaxb.impl.String {

  @XmlAttribute(name = "partialIndicator",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/")
  protected java.lang.Boolean partialIndicator;

  @XmlAttribute(name = "truncationIndicator",
    namespace = "http://release.niem.gov/niem/niem-core/5.0/")
  protected java.lang.Boolean truncationIndicator;

  @XmlAttribute(name = "lang",
    namespace = "http://www.w3.org/XML/1998/namespace")
  protected java.lang.String lang;

  /**
   * Gets the value of the partialIndicator property.
   *
   * @return
   * possible object is
   * {@link java.lang.Boolean }
   *
   */
  public java.lang.Boolean isPartialIndicator() {

    return partialIndicator;
  }

  /**
   * Sets the value of the partialIndicator property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.Boolean }
   *
   */
  public void setPartialIndicator(final java.lang.Boolean value) {

    this.partialIndicator = value;
  }

  /**
   * Gets the value of the truncationIndicator property.
   *
   * @return
   * possible object is
   * {@link java.lang.Boolean }
   *
   */
  public java.lang.Boolean isTruncationIndicator() {

    return truncationIndicator;
  }

  /**
   * Sets the value of the truncationIndicator property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.Boolean }
   *
   */
  public void setTruncationIndicator(final java.lang.Boolean value) {

    this.truncationIndicator = value;
  }

  /**
   * Gets the value of the lang property.
   *
   * @return
   * possible object is
   * {@link java.lang.String }
   *
   */
  public java.lang.String getLang() {

    return lang;
  }

  /**
   * Sets the value of the lang property.
   *
   * @param value
   * allowed object is
   * {@link java.lang.String }
   *
   */
  public void setLang(final java.lang.String value) {

    this.lang = value;
  }

}
